config/routes.rb
Rails.application.routes.draw do
  
  root to: 'toppages#index'
  
  get 'start',to: 'toppages#start'
  get 'stop',to: 'toppages#stop'
  
  get 'signup',to: 'users#new'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'task_and_memo', to: 'toppages#task_and_memo'
  get 'posts', to: 'toppages#post'
  
  get 'all_post', to: 'toppages#all_post'
  get 'my_post', to: 'toppages#my_post'
  
  resources :users,only: [:edit,:create,:update]
  resources :tasks,only: [:update,:edit,:create,:destroy]
  resources :posts,only: [:create,:destroy]
  resources :memos,only: [:update,:edit,:create,:destroy]
  
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    if logged_in?
      @post = current_user.posts.build  
      @posts = Post.all.order(id: :desc).page(params[:page])
      @memo = current_user.memos.build  
      @memos = current_user.memos.order(id: :desc).page(params[:page])
      @task = current_user.tasks.build  
      @tasks = current_user.tasks.order(id: :desc).page(params[:page])
    end
  end
  
  def task_and_memo
    @memo = current_user.memos.build  
    @memos = current_user.memos.order(id: :desc).page(params[:page])
    @task = current_user.tasks.build  
    @tasks = current_user.tasks.order(id: :desc).page(params[:page])
    @post = current_user.posts.build  
    @posts = Post.all.order(id: :desc).page(params[:page])
    # render 'toppages/task_memo'
    
  end
  
  def post
    @memo = current_user.memos.build  
    @memos = current_user.memos.order(id: :desc).page(params[:page])
    @task = current_user.tasks.build  
    @tasks = current_user.tasks.order(id: :desc).page(params[:page])
    @post = current_user.posts.build  
    @posts = Post.all.order(id: :desc).page(params[:page])
  end
  
  def all_post
    @post = current_user.posts.build  
    @posts = Post.all.order(id: :desc).page(params[:page])
  end
  
  def my_post
    @post = current_user.posts.build  
    @posts = current_user.posts.order(id: :desc).page(params[:page])
  end
  
  def start
  end
  
  def stop
  end
end

app/views/toppages/_post.html.erb
<div class="col-sm-12">
  <%= render 'posts/index' %>  
</div>

app/views/toppages/_task_memo.html.erb
<aside class="col-sm-4">
  <%= render 'tasks/index' %>  
</aside>
<div class="col-sm-8">
  <%= render 'memos/index' %>  
</div>

app/views/toppages/all_post.js.erb
$("#posts-box").html("<%= escape_javascript(  render 'posts/posts',posts: @posts) %>");
$("#my_post_tab").removeClass('active');
$("#all_post_tab").addClass('active');

app/views/toppages/index.html.erb
  <div class="center jumbotron">
      <div class="text-center">
        <% if logged_in?  %>
          <h1 id="timer"><%= current_user.work %>:00</h1>
        <% else %>
          <h1 id="timer">25:00</h1>
        <% end %>
        </h1>
        <%= link_to 'START', start_path, class: 'btn btn-lg btn-primary', id: "start_button",remote: true %>
        <%= link_to 'STOP', stop_path, class: 'btn btn-lg btn-primary', id: "stop_button",remote: true %>
      </div>
  </div>
  
<% if logged_in? %>
  <ul class="nav nav-tabs nav-justified mb-3">
    
    <li class="nav-item"><%= link_to 'task & memo',task_and_memo_path,id:"task_memo_tab",class:"nav-link active",remote: true %></li>
    <li class="nav-item"><%= link_to 'post',posts_path,id:"post_tab",class:"nav-link",remote: true %></li>
  </ul>
  <div class="row" id="contents-box">
    <%= render 'toppages/task_memo' %>
  </div>
  
  <script>
    work=<%= current_user.work %>
    short_break=<%= current_user.short_break %>
    long_break=<%= current_user.long_break %>
    is_work=<%= current_user.is_work %>
    work_count=<%= current_user.today_work_count %>
    
    window.onbeforeunload=set_lasttime;
    window.onload=function(){
      restore_lasttime();
    };
  </script>
<% else %>
  <h1>What's Pomodoro?</h1>
  <p style="white-space: pre-wrap;">
    ポモドーロタイマーは、生産性を飛躍的に向上させるツールです。
    仕事をずっと続けてしまって、疲れてしまって逆に効率が落ちてしまった経験はありませんか?
    ポモドーロタイマーは、そんなあなたのためにあります。
    仕組みは基本的に、シンプルです。
    仕事や勉強の時間と休憩の時間を管理してくれます。
    仕事や勉強の時間は、デフォルトでは25分になっています。
    休憩の時間は2種類あります。短い休憩と長い休憩があります。
    こちらは、デフォルトでは、短い休憩が5分、長い休憩が15分となっています。
    タイマーは、0になった状態で、ストップを押すことで、自動的に次の時間がセットされます。
    仕事の時間、短い休憩の時間を3セット終えたら、次は、仕事の時間、長い休憩の時間がセットされます。
    
    時間を決めて、きっちり働き、休む時は、きっちり休む。その効果をぜひ一度お試しください。
    サインアップしていただけると、タイマーのデフォルトの時間設定を変えて頂けるようになります。
    また、タスクを管理する機能、学びのを残すメモ機能、学びを他のユーザと
    共有していただけるつぶやきの機能がご利用いただけます。
    
  </p>
<% end %>

app/views/toppages/my_post.js.erb
$("#posts-box").html("<%= escape_javascript(  render 'posts/posts',posts: @posts) %>");
$("#all_post_tab").removeClass('active');
$("#my_post_tab").addClass('active');

app/views/toppages/post.js.erb
$("#contents-box").html("<%= escape_javascript(  render 'toppages/post') %>");
$("#task_memo_tab").removeClass('active');
$("#post_tab").addClass('active');

app/views/toppages/start.js.erb
tick();

app/views/toppages/stop.js.erb
function stop(){
    clearInterval(timer);
    is_counting=false;
    if(is_work && get_timer_string()=="00:00"){
        work_count+=1;
        is_work=false;
        if(work_count%4!=0){
            minute_string=("0"+String(short_break)).slice(-2);
        }else{
            minute_string=("0"+String(long_break)).slice(-2);
        }
        second_string="00";
        set_timer_string();
        
    }
    if(!is_work && get_timer_string()=="00:00"){
        is_work=true;
        minute_string=("0"+String(work)).slice(-2);
        second_string="00";
        set_timer_string();
    }

    
    start_button.disabled=false;
    oscillator.stop();
    isPlaying = false;
}

stop();

app/views/toppages/task_and_memo.js.erb
$("#contents-box").html("<%= escape_javascript(  render 'toppages/task_memo') %>");
$("#post_tab").removeClass('active');
$("#task_memo_tab").addClass('active');