config/routes.rb
Rails.application.routes.draw do
  
  root to: 'toppages#index'
  
  get 'start',to: 'toppages#start'
  get 'stop',to: 'toppages#stop'
  
  get 'signup',to: 'users#new'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'task_and_memo', to: 'toppages#task_and_memo'
  get 'posts', to: 'toppages#post'
  
  get 'all_post', to: 'toppages#all_post'
  get 'my_post', to: 'toppages#my_post'
  
  resources :users,only: [:edit,:create,:update]
  resources :tasks,only: [:update,:edit,:create,:destroy]
  resources :posts,only: [:create,:destroy]
  resources :memos,only: [:update,:edit,:create,:destroy]
  
end

app/models/post.rb
class Post < ApplicationRecord
    validates :content,presence: true,length: {maximum: 255}
    belongs_to :user
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:destroy]
  
  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = 'つぶやきを投稿しました。'
      redirect_to root_url
    else
      @post = current_user.posts.build  
      @posts = Post.all.order(id: :desc).page(params[:page])
      @memo = current_user.memos.build  
      @memos = current_user.memos.order(id: :desc).page(params[:page])
      @task = current_user.tasks.build  
      @tasks = current_user.tasks.order(id: :desc).page(params[:page])      
      flash.now[:danger] = 'つぶやきの投稿に失敗しました。'
      render 'toppages/index'
    end
  end

  def destroy
    @post.destroy
    flash[:success] = 'つぶやきを削除しました。'
    redirect_back(fallback_location: root_path)
  end

  private

  def post_params
    params.require(:post).permit(:content)
  end

  def correct_user
    @post = current_user.posts.find_by(id: params[:id])
    unless @post
      redirect_to root_url
    end
  end
end

app/views/posts/_form.html.erb
<%= form_with(model: @post, local: true) do |f| %>
    <div class="form-group">
          <%= f.text_area :content, class: 'form-control', rows: 5 %>
    </div>
    <%= f.submit 'Add', class: 'btn btn-primary btn-block' %>
<% end %>

app/views/posts/_index.html.erb
<div class="row">
<aside class="col-sm-4">
  <h1>Posts</h1>
    <%= render 'posts/form',posts: @posts %>
</aside>
<div class="col-sm-8">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><%= link_to "all post",all_post_path,class:"nav-link active",id:"all_post_tab",remote: true %></li>
      <li class="nav-item"><%= link_to "my post",my_post_path,class:"nav-link",id:"my_post_tab",remote: true %></li>
    </ul>
    <div id="posts-box">
      <%= render 'posts/posts', posts: @posts %>  
    </div>
    
</div>

app/views/posts/_posts.html.erb
<ul class="list-unstyled">
  <% posts.each do |post| %>
    <li class="media mb-3">
      <img class="mr-2 rounded" src="<%= gravatar_url(post.user, { size: 50 }) %>" alt="">
      <div class="media-body">
        <div>
          <%= link_to post.user.name, user_path(post.user) %> <span class="text-muted">posted at <%= post.created_at %></span>
        </div>
        <div>
          <p class="mb-0"><%= post.content %></p>
        </div>
        <div>
          <% if current_user == post.user %>
            <%= link_to "Delete", post, method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-danger btn-sm' %>
          <% end %>
        </div>
      </div>
    </li>
  <% end %>
  <%= paginate posts %>
</ul>