config/routes.rb
Rails.application.routes.draw do
  
  root to: 'toppages#index'
  
  get 'start',to: 'toppages#start'
  get 'stop',to: 'toppages#stop'
  
  get 'signup',to: 'users#new'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'task_and_memo', to: 'toppages#task_and_memo'
  get 'posts', to: 'toppages#post'
  
  get 'all_post', to: 'toppages#all_post'
  get 'my_post', to: 'toppages#my_post'
  
  resources :users,only: [:edit,:create,:update]
  resources :tasks,only: [:update,:edit,:create,:destroy]
  resources :posts,only: [:create,:destroy]
  resources :memos,only: [:update,:edit,:create,:destroy]
  
end

app/models/memo.rb
class Memo < ApplicationRecord
    validates :content,presence: true,length: {minimum: 1,maximum: 500}
    belongs_to :user
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  before_action :require_user_logged_in
  before_action :set_memo,only: [:edit,:update,:destroy]
  
  
  def edit
    
  end
  
  def update
    if @memo.update(memo_params)
      flash[:success] = 'メモを更新しました。'
      redirect_to root_url
    else
      @memos = current_user.memos.order(id: :desc).page(params[:page])
      flash.now[:danger] = 'メモの更新に失敗しました。'
      render 'edit'
    end
  end
  def create
    @memo = current_user.memos.build(memo_params)
    if @memo.save
      flash[:success] = 'メモを作成しました。'
      redirect_to root_url
    else
      @memos = current_user.memos.order(id: :desc).page(params[:page])
      flash[:danger] = 'メモの作成に失敗しました。'
      redirect_to root_url
    end
  end

  def destroy
    @memo.destroy
    flash[:success] = 'メモを削除しました。'
    redirect_back(fallback_location: root_path)
  end

  private
  
  def set_memo
    @memo=Memo.find(params[:id])
  end

  def memo_params
    params.require(:memo).permit(:content)
  end

end

app/views/memos/_form.html.erb
<%= form_with(model: @memo, local: true) do |f| %>

    
    <div class="form-group">
          <%= f.text_area :content, class: 'form-control', rows: 5 %>
    </div>
    <%= f.submit 'Add', class: 'btn btn-primary btn-block offset-sm-11 col-sm-1' %>
<% end %>

app/views/memos/_index.html.erb
<h1>Memos</h1>
<div class="w-100" style="margin-bottom:10px;">
    <%= render 'memos/form',memos: @memos %>
</div>

<div class="w-100">
    <%= render 'memos/memos', memos: @memos %>
</div>

app/views/memos/_memos.html.erb
<ul class="list-unstyled">
  <% @memos.each do |memo| %>
    <li class="media mb-3">
      
      <div class="media-body">
        <div>
          <%= memo.created_at %></span>
        </div>
        <div>
          <textarea class="w-100 mb-0 my_textarea" readonly><%= memo.content %></textarea>
          
        </div>
        <div>
          <%= link_to "Edit",edit_memo_path(memo),class: "btn btn-success btn-sm" %>
          <%= link_to "Delete", memo, method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-danger btn-sm' %>  
        </div>
      </div>
    </li>
  <% end %>
  <%= paginate memos %>
</ul>

app/views/memos/edit.html.erb
<h1>メモ編集ページ</h1>

<%= form_with(model: @memo, local: true) do |f| %>
  <%= render 'layouts/error_messages',model: f.object %>

  <%= f.text_area :content,class: 'w-75' %>

  <%= f.submit 'Update',class:"btn btn-primary btn-sm" %>
<% end %>

<%= link_to 'トップページに戻る', root_path %>